### ISSUE TITLE
请问如何正确运行？

### ISSUE THREAD

**Issue by sola614** [wushuo894/EmbyPinyin#2]
用docker compose部署后，日志看不出，然后emby媒体库新增了几个番剧，过了几天也没效果，日志如下：
```
stdout: [2024-09-19 10:16:56] [DEBUG] cn.hutool.log.LogFactory: Use [Hutool Console Logging] Logger As Default.
stdout: Hutool Simple Http Server listen on 【0:0:0:0:0:0:0:0:9198】
stdout: [2024-09-19 10:16:57] [INFO] com.emby.Main: adminUserId => 58f7b0b909fb483089db537c018ecd3f
stdout: [2024-09-23 22:56:29] [DEBUG] cn.hutool.log.LogFactory: Use [Hutool Console Logging] Logger As Default.
stdout: Hutool Simple Http Server listen on 【0:0:0:0:0:0:0:0:9198】
stdout: [2024-09-23 22:56:30] [INFO] com.emby.Main: adminUserId => 58f7b0b909fb483089db537c018ecd3f
```
docker-compose.yml配置如下：
```
version: '3.8'
services:
  emby-pinyin:
    container_name: emby-pinyin
    image: wushuo894/emby-pinyin:latest
    restart: unless-stopped
    ports:
      - 7014:9198
    environment:
      - TZ=Asia/Shanghai
      - CRON=0 3 * * *
      - HOST=http://192.168.0.1:7568
      - KEY=xxx
      - ITEM="-"
```
emby是docker部署的开心版，暴露的端口是7568->8096，进入embypinyin容器利用wget命令是可以访问到http://192.168.0.1:7568，希望能指导下

**Comment by wushuo894** [comment]
你没有设置KEY啊

在 emby-设置-高级-API密钥 生成一个并填入

**Comment by sola614** [comment]
有填的，我这里只不过用xxx代替

**Comment by wushuo894** [comment]
设置RUN为TRUE，看看有在运行吗

**Comment by sola614** [comment]
加上rebuild之后就这个日志：
```
stdout: [2024-09-23 23:18:23] [DEBUG] cn.hutool.log.LogFactory: Use [Hutool Console Logging] Logger As Default.
stdout: Hutool Simple Http Server listen on 【0:0:0:0:0:0:0:0:9198】
stdout: [2024-09-23 23:18:25] [INFO] com.emby.Main: adminUserId => 58f7b0b909fb483089db537c018ecd3f
```

**Comment by sola614** [comment]
配置：
```
version: '3.8'
services:
  emby-pinyin:
    container_name: emby-pinyin
    image: wushuo894/emby-pinyin:latest
    restart: unless-stopped
    ports:
      - 7014:9198
    environment:
      - TZ=Asia/Shanghai
      - CRON=0 3 * * *
      - HOST=http://192.168.0.1:7568
      - KEY=xxx
      - ITEM="-"
      - RUN=TRUE
```
